frequency: 30
sensor_timeout: 0.1

two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link

imu0: imu/data_raw
imu0_config: [false, false, false,   # x y z acceleration
              false, false, true,    # roll pitch yaw (angular velocity)
              false, false, false,   # linear accel (x, y, z)
              false, false, false]   # angular velocity (x, y, z)

odom0: wheel/odometry
odom0_config: [true, true, false,   # x y position
               false, false, true,  # roll pitch yaw
               true, true, false,   # linear velocity (x, y)
               false, false, true]  # angular velocity (z)
