local_costmap:
    global_frame: map
    robot_base_frame: base_link
<<<<<<< HEAD
    update_frequency: 5.0  # Increased for faster updates
    publish_frequency: 2.0

    static_map: false
    rolling_window: true
    width: 1.5
    height: 1.5
    resolution: 0.05
=======
    update_frequency: 10  # Increased for faster updates
    publish_frequency: 5.0

    static_map: false
    rolling_window: true
    width: 2.5
    height: 2.5
    resolution: 0.1
>>>>>>> 77d0c76948a66632b3bf7148c1832289837f4468

    plugins:
        - {name: static_layer, type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    obstacle_layer:
        observation_sources: lidar_sensor
        footprint_clearing_enabled: true
        lidar_sensor: 
            data_type: LaserScan
            sensor_frame: laser
            topic: /scan
            marking: true
            clearing: true

    inflation_layer:
        enabled: true
        cost_scaling_factor: 5.0  
        inflation_radius: 0.05  # Increased for smoother avoidance
